controller_list:
  - name: "position_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
