<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="kuka_adapter_plate" params="prefix radius height">

        <link name="${prefix}adapter_plate">
            <visual>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${height}"/>
                </geometry>
                <material name="">
                    <color rgba="0.05 0.05 0.05 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${height}"/>
                </geometry>
            </collision>
        </link>

        <link name="${prefix}adapter_plate_mount_frame"/>

        <joint name="${prefix}pedestal_mount_joint" type="fixed">
            <origin xyz="0 0 ${height}" rpy="0 0 0"/>
            <parent link="${prefix}adapter_plate"/>
            <child link="${prefix}adapter_plate_mount_frame"/>
        </joint>

    </xacro:macro>

</robot>
