controller_list:
  - name: "ag1/position_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [ag1_joint_1, ag1_joint_2, ag1_joint_3, ag1_joint_4, ag1_joint_5, ag1_joint_6]
  - name: "ag2/position_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [ag2_joint_1, ag2_joint_2, ag2_joint_3, ag2_joint_4, ag2_joint_5, ag2_joint_6]
