controller_list:
  - name: fake_agilus1_controller
    joints:
      - ag1_joint_1
      - ag1_joint_2
      - ag1_joint_3
      - ag1_joint_4
      - ag1_joint_5
      - ag1_joint_6
  - name: fake_agilus2_controller
    joints:
      - ag2_joint_1
      - ag2_joint_2
      - ag2_joint_3
      - ag2_joint_4
      - ag2_joint_5
      - ag2_joint_6