controller_list:
  - name: "ag1/position_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [ag1_joint_a1, ag1_joint_a2, ag1_joint_a3, ag1_joint_a4, ag1_joint_a5, ag1_joint_a6]
  - name: "ag2/position_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [ag2_joint_a1, ag2_joint_a2, ag2_joint_a3, ag2_joint_a4, ag2_joint_a5, ag2_joint_a6]
