controller_list:
  - name: fake_agilus1_controller
    joints:
      - ag1_joint_a1
      - ag1_joint_a2
      - ag1_joint_a3
      - ag1_joint_a4
      - ag1_joint_a5
      - ag1_joint_a6
  - name: fake_agilus2_controller
    joints:
      - ag2_joint_a1
      - ag2_joint_a2
      - ag2_joint_a3
      - ag2_joint_a4
      - ag2_joint_a5
      - ag2_joint_a6