#Publish all joint states
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Joint trajectory controller
position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - qu2_joint_a1
        - qu2_joint_a2
        - qu2_joint_a3
        - qu2_joint_a4
        - qu2_joint_a5
        - qu2_joint_a6
    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
